### ISSUE TITLE
[RFC] Generate variables with build process

### ISSUE THREAD

**Issue by jlaswell** [heybokeh/pollen#46]
Thank you. This project is great. Simple, easy, and high value. I really appreciate this. And while I'm happy to just build, build, build with the defaults, we have some design standards that fall outside of those defaults.

Our current solution is overrides, but I can already see value in being able to generate values instead for the variables already defined in pollen. Both the colors addon and https://github.com/heybokeh/pollen/issues/42 are features that could leverage this.

Is there interest in supporting something like this as part of this project?

---

Example: Pseudo-TypeScript method of defining gray as `#1e1e20` could yield this overly verbose result.

```typescript
type Colors = {
  gray?: string;
  // other colors
}

let brandColors: Colors = {
  gray: "#1e1e20",
  // other colors
};

Pollen.build(brandColors);
```

```css
    --color-gray-rbg: 30, 30, 30;
    --color-gray-100: #1e1e1e;
    --color-gray-80:  #4a4a4a;
    --color-gray-60:  #777777;
    --color-gray-40:  #a3a3a3;
    --color-gray-24:  #c7c7c7;
    --color-gray-16:  #d8d8d8;
    --color-gray-08:  #eaeaea;
    --color-gray-80a: rgba(var(--color-gray-rbg), .8);
    --color-gray-60a: rgba(var(--color-gray-rbg), .6);
    --color-gray-40a: rgba(var(--color-gray-rbg), .4);
    --color-gray-24a: rgba(var(--color-gray-rbg), .24);
    --color-gray-16a: rgba(var(--color-gray-rbg), .16);
    --color-gray-08a: rgba(var(--color-gray-rbg), .08);
```

**Comment by madeleineostoja** [comment]
Yes! I’ve been thinking about this too. It would be great to have all of pollen’s design tokens generated out of a set of defaults, so a user can import the built CSS directly as they do now or use the build tool to generate their own set by extending defaults.

Sort of the same as tailwind’s config file, except it’d be a one time build.

It’d be a pretty big chunk of work so I wouldn’t be able to get to it any time soon, happy to accept PRs though.

**Comment by madeleineostoja** [comment]
And I agree that addons like colour and typesets in particular would benefit a lot from this. In my own work I find the default colour palette of limited use since every project has it’s own palette, and you can’t avoid typesets being pretty opinionated and therefore also of limited general use (which is why I haven’t published them yet, and am leaning towards leaving them out).

I can’t think off the top of my head how you’d reconcile core modules and addons in a single build tool (does it spit out seperate files? That would be annoying to consume. Do you specify what chunks go in what files? Starting to get complex. Etc), but it’s worth thinking through imo

**Comment by madeleineostoja** [comment]
Thinking more about this (in the 10min since I first replied lol) I think it could be a very cool idea, turning Pollen into a design system generator with defaults rather than just a collection of CSS files. My only concern is introducing complexity, since one of the big benefits of Pollen is its simplicity, with no config file or buildstep. So I'd definitely want a bit of community feedback before committing to anything.

With that said, how's this for a very rough back-of-the-napkin sketch of a potential API:

----

#### Use default core variables

Nothing changes

```js
import 'pollen-css/pollen.css`;
```

#### Generate default core variables

Empty config file with pollen builder

_pollen.config.js_
```js
module.exports = function() {
  return {}
}
```

Run pollen cli, defaults to outputting `./pollen.css`
```sh
$ pollen
```

#### Enable addons

No more prebuilt addon CSS files, enable each family in them in config and build a custom `pollen.css` bundle by passing `true` to the top level config options

_pollen.config.js_
```js
module.exports = function() {
  return {
    // Core (true by default)
	typography: true,
	layout: true,
	ui: true,

	// Addons (false by default)
	colors: true,
	grid: true
  }
}
```

Output to custom dir
```sh
$ pollen -o src/styles/_pollen.css
```

#### Change value of defaults

Passing an object to a config option overwrites all defaults, use the provided `pollen` object in the config function to spread defaults and extend them. Fairly verbose but feels less magical than extending by default or tailwind's odd `extend` key.

_pollen.config.js_
```js
module.exports = function(pollen: PollenDefaults) {
  return {
	 typography: {
		...pollen.typography,
		line: {
		  ..pollen.typography.line,
 		  md: 1.6
		}
     }
  }
}
```

#### Extend defaults

Add a new key to a config option to create a new variable in that family

_pollen.config.js_
```js
module.exports = function(pollen: PollenDefaults) {
  return {
	 typography: {
		...pollen.typography,
		line: {
		  ..pollen.typography.line,
 		  xxs: 1.1
		}
     }
  }
}
```

Generates `--line-xxs: 1.1`

#### Add new custom output

Add config objects to a `custom` key, where each object is a new family and its keys are `[family]-[key]` items

_pollen.config.js_
```js
module.exports = function(pollen: PollenDefaults) {
  return {
	colors: true,
    custom: {
	  gradient: {
		grey: `linear-gradient(var(--color-grey-300), var(--color-grey-500))`,
		blue: `linear-gradient(var(--color-blue-300), var(--color-blue-500))`
	 }
  }
}
```

Generates a new family of variables, up to the user to ensure any dependencies they use are enabled in config

```css
--gradient-grey: linear-gradient(var(--color-grey-300), var(--color-grey-500));
--gradient-blue: linear-gradient(var(--color-blue-300), var(--color-blue-500));
```

#### Thoughts

Not sure about the top-level keys (`typography`, etc), the only benefit of the former is quicker config, enabling/disabling a whole addon or core module at once. The alternative is to have every family at the top level of config. This would make it a lot more transparent (no need for `custom` config object, every key is a family), but way more verbose. 

Eg:
```js
module.exports = function() {
  return {
    // Core modules
	scale: true,
	font: true,
	line: true,
	letter: true,
	prose: true,
	size: true,
	width: true,
	radius: true,
	elevation: true,
	blur: true,
	easing: true,
	layer: true,

	// Addons
	color: true,
	gridPage: true,
	grid: true

	// Custom
	gradient: {...}
}
```

**Comment by crhallberg** [comment]
As long as the default css remains useful and reasonably small, I think this level of control would be very useful. I wonder if we can tie this into purgeCSS somehow to automatically disable addons.

**Comment by madeleineostoja** [comment]
What benefit would purgeCSS give? Under this proposal you’d just pass false to the addons in config to exclude them from the generated bundle

**Comment by jlaswell** [comment]
Thanks for being open to this idea.

> It’d be a pretty big chunk of work for a limited use-case (overriding with plain CSS variables is usually fine unless you’re doing a big overhaul)

We're that limited use case. 🙃 Sounds like there's a desire to keep this simple and easily consumable, which I wanted to mention. I don't want to bring an idea that ruins the first line of the getting started page. I'd be open to the build process living as a separate repo to actually build heybokeh/pollen, but if the build process lives alongside here too, I'd still +1 that.

---

From there, I like the ideas for the ability to merge, extend, and add custom variables. I think there may be potential around a concept of ratios as well. That may be outside the scope of desired support here too.

```scss
.text {
  font-size: var(--scale-0);   /* 16px */
  line-height: var(--scale-3); /* 24px */

  &--secondary {
    font-size: var(--scale-00); /* 14px */
    line-height: var(--scale-2); /* 20px */
  }
}

.header {
  /**
   * I need 32px/40px. :(
   *
   * --scale-4: 1.875rem or 30px
   * --scale-5: 2.25rem or 36px
   * --scale-6: 3rem; /* 48px */
   */
  font-size: var(--size-8);
  line-height: var(--size-10);
}
```

Instead of having to define every size/scale in the *pollen.config.js* file, some sort of scaling/ratio would be valuable. 

```ts
module.exports = function(pollen: PollenDefaults, merge) {
    return {
        typography: merge(pollen.typography, {
            scale: {
                // linear scaling could be PollenDefaults.scale.linear
                func: (val: number, rate: number) => PollenDefaults.scale.linear,
            },
        }
    )};
}
```

and yields the following.

```css
  --scale-000: 0.5rem;
  --scale-00:  0.75rem;
  --scale-0:   1rem;
  --scale-1:   1.25rem;
  --scale-2:   1.5rem;
  /* ... */
```

**Comment by madeleineostoja** [comment]
Well as long as it's sync you'd be able to run any logic you like in the config, all it would have to do is return key:value pairs. I'm not sure it'd be worth having things like scales in the pollen defaults though, it'd be easy enough to do that with userland logic/math. This is how Pollen's existing `size` scale for example would be generated. In my mind the provided default config should just literally be a bag of all the key:value pairs used by default, so it's easy to understand and extend, and doesn't need documentation beyond what we already have / what is generated. This is the same way Tailwind's config works (except they use a special `extend` key rather than explicitly merging defaults) and that seems to be easily understood.

I think if this was to be implemented it should definitely be a part of Pollen core, since I don't know how you'd reconcile addons + core modules other than changing the methodology to enabling them in config vs. consuming extra prebuilt CSS files.

**Comment by madeleineostoja** [comment]
So this was actually easier than I thought it would be, I have a POC that I'll push up in a branch for people to try soon 🚀

**Comment by madeleineostoja** [comment]
Published under `v3.2.0-beta.1` with zero breaking changes 🥳

```
npm i pollen-css@beta
```

I don't have time to write docs for this yet, but the interface largely matches what I outlined in my first lengthy comment, with a small adjustment:

_pollen.config.js_
```js
/** @type {import('pollen-css').Config} */
module.exports = (pollen, merge) => {
	return {
		output: 'pollen.css' // default value,
		modules: {
			// Config API outlined previously
		}
	}
}
```

```sh
$ pollen 
```

Currently I'm generating the old prebuilt addon files with pollen build configs so there's no breaking changes, but I'd like to hard deprecate them at some point in favour of config only. And assuming this new generative approach feels good and we stick with it, I want to release as a minor version so we have leeway to change the config API at some point without _another_ major version breaking change.

Pull it down and let me know what you think!

**Comment by madeleineostoja** [comment]
Few things to think about re: config API I don't have answers for atm:

- Some modules use the same prefix, ie: font families and font weights both use `font-`. Currently they're both shoehorned into `font: {...}`, which seems hacky. Most robust solution is adding the prefix as a config key for every submodule, but it makes the config way more verbose. Another option is just... don't repeat prefixes. Split font weight into `--font-weight-` for v4
- Some tools would be good to have abstracted config, namely typesets. Tailwind's typeset config is quite concise compared to writing cumbersome CSS strings. However this breaks the current parsing logic, and you'd need to add stuff to handle each one of these custom cases. Not an issue until/whether we add typesets imo

**Comment by madeleineostoja** [comment]
Up to date example config in https://github.com/heybokeh/pollen/issues/47

(Flattened module config, removed merge utility)

**Comment by madeleineostoja** [comment]
Something to think about — do we use the object keys as variable prefix (how the POC works atm), or specify a prefix explicitly for each module? Former is simpler, terser, and quicker, but feels like it could be brittle. The latter is more robust and flexible, and adds another layer to config api which makes everything a little more cumbersome.

Eg:

```is
{
  fontWeight: (
    prefix: ‘weight’,
    values: { … } 
  )
)
```

**Comment by jlaswell** [comment]
Commenting on a closed issue to say thanks and this looks awesome! Circling back to this over the next week to try it out! 🎉

**Comment by madeleineostoja** [comment]
Thanks for the suggestion!! Makes Pollen a _much_ more useful and powerful tool :)
