### ISSUE TITLE
Colors: colorful (warm/cold) greys

### ISSUE THREAD

**Issue by daniel-j-h** [heybokeh/pollen#58]
Hey folks, I'm playing around with pollen and really like it so far :heart: 

I'm using greys as a base for my pages and want to give them a slight touch of color - most often a cold (blue'ish) or a warm (yellow'ish) touch, to make the overall page design feel either colder or warmer.

What I'm doing so far is taking the pollen greys to a color picker and then adding a touch of blue/yellow eye-balling the results.

Do you think this is a use case pollen should support in its color palette?

I have been looking at [the competition](https://tailwindcss.com/docs/customizing-colors) :eyes: :see_no_evil: how they do it, and it seems like they have Slate and Stone for cold/warm greys, respectively.

**Comment by madeleineostoja** [comment]
Could do! It would be a breaking change though so I feel it would need a pretty compelling use-case. And since the colour palette is easy to extend or customise in userland I’m not sure it’s worth it. Very open to more input though

**Comment by enyo** [comment]
I don't personally have any use for this right now but adding grey values like this for rapid prototyping seems quite useful to me. Of course you can define the colors yourself but a main advantage of using libraries like pollen is that you get useful defaults out of the box. 

Maybe instead of a breaking change it would make sense to add a neutral grey instead?
