### ISSUE TITLE
Custom colors not in exported JSON

### ISSUE THREAD

**Issue by frizzant** [heybokeh/pollen#75]
When exporting a JSON file, the custom colors seem not to be represented in the `pollen.json` file.

```
module.exports = (pollen) => ({
  output: {
    css: './.pollen/pollen.css',
    json: './.pollen/pollen.json'
  },
  modules: {
    color: { ...pollen.color, custom: '#AAAAAA' },
  }
})
```

I am assuming this is intentional. It would be nice to have them represented in that file, or having an option for that.

**Comment by shannonrothe** [comment]
I added the functionality to export to JSON but didn't consider including custom configuration for any of the modules. Currently it will just write the default modules (as you've observed) here:

https://github.com/heybokeh/pollen/blob/1e2bb097930267685e6a055b45b88b9822b8eb76/src/index.ts#L66

@madeleineostoja I'm happy to pick this is up if you're happy with the suggestion of including custom module values? 😄

**Comment by madeleineostoja** [comment]
Whoops sorry missed this! Yes the whole point of the JSON export is to serve as internal documentation if your config deviates significantly from the defaults, so this is a must-have. PR looks good 👍 I think a simple spread like that should be fine since no config keys will be more than one level deep. Once/if we introduce more complex config (ie: for queries) then we'd prob need a deep merge, but this'll do for now
