### ISSUE TITLE
system-ui in --font-sans font stack

### ISSUE THREAD

**Issue by daniel-j-h** [heybokeh/pollen#85]
Hey folks, I'm just seeing that we have system-ui in the sans font variable

https://github.com/heybokeh/pollen/blob/dc34314ae45d3ca55f5308491451d9169fc1f084/src/modules/typography.ts#L53

and I was wondering if we should remove it as a default, since it's problematic for some users
- https://infinnie.github.io/blog/2017/systemui.html
- https://news.ycombinator.com/item?id=31543054

At the moment I work around it by overwriting the default in my project via

    :root { --font-sans: .. }

Also wondering how we came up with the font stack, and if we can rely on something like https://systemfontstack.com?

**Comment by madeleineostoja** [comment]
I was under the impression that system-ui had significantly stabilised since those concerns? If that’s not the case then yep we can strip it out. Most production projects will overwrite these particular defaults anyway.

The current font stacks were taken from a postcss shim for system-ui, but your source looks v solid as well. Next time there’s a breaking change on the cards it would be worth updating them regardless.

As an aside it’ll be cleaner to overwrite / change anything you need in pollen with a [config file](https://www.pollen.style/basics/configuration) rather than clobbering output css variables :)

**Comment by daniel-j-h** [comment]
From what I can see, system-ui still has its problems, but I also understand that this change would require a new pollen release.

Thanks for the config pointers, looks awesome to customize pollen so easily with a config file! I'll look into it! :raised_hands:

**Comment by madeleineostoja** [comment]
Doing some old issue cleanup, after some research looks like the system-ui font issues are resolved now, Bootstrap et al [added it back into their stacks](https://github.com/twbs/bootstrap/pull/30561/files) which is good enough for me
